# Generated by Django 5.1.5 on 2025-02-03 09:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_comment='The full name of the person submitting the contact form.', help_text='Please enter your full name.', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(db_comment='The email address of the person submitting the contact form.', help_text='Please enter a valid email address.', max_length=254, verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_comment='The phone number of the person submitting the contact form.', help_text='Please enter a valid phone number.', max_length=128, region='IR', verbose_name='Phone Number')),
                ('subject', models.CharField(db_comment='The subject of the contact request.', help_text='Please enter the subject of your message.', max_length=255, verbose_name='Subject')),
                ('message', models.TextField(db_comment='The main body of the contact request.', help_text='Please enter your message.', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when the contact form was submitted.', help_text='The date and time when the contact form was submitted.', verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact_messages',
                'db_table_comment': 'Table storing contact messages submitted via the website.',
                'ordering': ['-created_at'],
            },
        ),
    ]
