# Generated by Django 5.1.5 on 2025-02-03 10:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(db_comment='Stores the detailed description of the instrument.', help_text='Provide a detailed description of the musical instrument, including features and specifications.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='description_fa',
            field=django_ckeditor_5.fields.CKEditor5Field(db_comment='Stores the detailed description of the instrument.', help_text='Provide a detailed description of the musical instrument, including features and specifications.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='title_en',
            field=models.CharField(db_comment='Stores the unique title of the instance.', help_text='Enter a unique title.', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='title_fa',
            field=models.CharField(db_comment='Stores the unique title of the instance.', help_text='Enter a unique title.', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
