# Generated by Django 5.1.5 on 2025-02-03 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_instrument_description_en_instrument_description_fa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instructors',
            field=models.ManyToManyField(db_comment="Many-to-many relationship with users who belong to the 'Instructor' group.", help_text='Select users who are instructors and associated with this instrument.', limit_choices_to={'groups__name': 'instructor'}, related_name='musical_instruments', to=settings.AUTH_USER_MODEL, verbose_name='Instructors'),
        ),
    ]
