# Generated by Django 5.1.5 on 2025-02-03 12:31

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_alter_instrument_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('alternate_text', models.CharField(blank=True, help_text='Write about picture for SEO', max_length=110, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)], verbose_name='Picture Alternate Text')),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Width", null=True, verbose_name='Picture Width')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Height", null=True, verbose_name='Picture Height')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, db_comment="Stores the user's profile description.", help_text='Provide a short biography or other relevant information about the user.', verbose_name='Description')),
                ('picture', sorl.thumbnail.fields.ImageField(db_comment='Profile image representing the user.', help_text='Upload a profile picture.', upload_to='profiles/pictures/', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(db_comment='One-to-one relationship with the user model.', help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'user_profiles',
                'db_table_comment': 'Table storing user profile information.',
            },
        ),
    ]
