# Generated by Django 5.1.5 on 2025-02-04 13:01

import django.core.validators
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('alternate_text', models.CharField(blank=True, help_text='Write about picture for SEO', max_length=110, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)], verbose_name='Picture Alternate Text')),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Width", null=True, verbose_name='Picture Width')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Height", null=True, verbose_name='Picture Height')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, db_comment='Stores images in the gallery.', help_text='Upload an image for the gallery.', null=True, upload_to='gallery/images/', verbose_name='Image')),
                ('video', models.FileField(blank=True, db_comment='Stores videos in the gallery.', help_text='Upload a video for the gallery.', null=True, upload_to='gallery/videos/', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'gallery',
                'db_table_comment': 'Table storing images and videos uploaded by users.',
            },
        ),
    ]
